server.port=8083
spring.application.name=appointment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.registry-fetch-interval-seconds=5

# Disable OTLP push metrics unless collector is running.
management.otlp.metrics.export.enabled=false

