server.port=8083
spring.application.name=appointment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.registry-fetch-interval-seconds=5

management.otlp.metrics.export.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=darkkill132@gmail.com
spring.mail.password=mcxd uelr ddgx avvb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

appointment.reminder.enabled=true
appointment.reminder.hours-before=24
appointment.reminder.fixed-delay-ms=900000

