server.port=8081

spring.application.name=user-service

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
eureka.client.registry-fetch-interval-seconds=5

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

user.seed.enabled=true
user.seed.admin-email=admin@barber.local
user.seed.admin-password=Admin1234
user.seed.barber-email=barber@barber.local
user.seed.barber-password=Barber1234
